name: Review Lockfile Updates

on:
  pull_request:
    branches: ['*']

concurrency:
  # Prevent parallel executions of this and related tasks.
  group: updating-chart-locks
  cancel-in-progress: false

env:
  # APPROVED_ACTOR is the GitHub user that can submit lockfile update PRs
  APPROVED_ACTOR: komish-impersonator

jobs:
  determine-if-lockfile-update:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR with automation label
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            repo: context.repo.repo,
            owner: context.repo.owner,
            labels: ['automation']
          })
    - name: Validate PR comes from Bot
      uses: actions/github-script@v6
      with:
        script: |
          const pr = await github.rest.pulls.get({
            repo: context.repo.repo,
            owner: context.repo.owner,
            pull_number: context.issue.number,
          });

          const prContributor = pr.data.user.login;
          
          if ( prContributor !== ${{ env.APPROVED_ACTOR }}) {
            core.setFailed(`User ${prContributor} cannot submit this PR. Approved actor is ${{ env.APPROVED_ACTOR }}`)
            return 1
          }
    - name: Get files modified in PR  
      uses: actions/github-script@v6
      id: read-pr-file-list
      with:
        script: |
          github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          })

          
